name: Deploy pkgdown site

on:
  push:
    branches:
      - gh-pages  # Trigger when you push to gh-pages
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: plger/metrics:latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("pkgdown")
        shell: Rscript {0}

      - name: Build the site
        run: |
          Rscript -e 'pkgdown::build_site()'  # Build the site

      - name: Commit and push the site to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global --add safe.directory /__w/poem/poem
          git add .
          git commit -m "Deploy updated pkgdown site" || echo "Nothing to commit"
          git push origin gh-pages  # Push to the gh-pages branch